REG-2 | render 1 random object
nazarrachunn/my-project pull request #2
Opened 2023-06-04 20:40 UTC by nazarrachunn

2023-06-05 15:24 UTC, taras-bilozir-globacap requested changes

2023-06-05 15:24 UTC, taras-bilozir-globacap commented on src/index.tsx
> +import "./index.css";
It's a typical approach to use single quote.

2023-06-05 15:24 UTC, taras-bilozir-globacap commented on src/App.tsx
> +        {<p>{JSON.stringify(randomItem)}</p>}
Should be:
`<p>{randomItem.title}</p>`

If you want to use JSON.stringify it should be used when you use "setRandomItem" function, otherwise it is executed many time after each rerender.

2023-06-05 15:24 UTC, taras-bilozir-globacap commented on src/index.tsx
>  // or send to an analytics endpoint. Learn more: https://bit.ly/CRA-vitals
Also remove comments.

2023-06-05 15:24 UTC, taras-bilozir-globacap commented on src/index.tsx
> +import reportWebVitals from "./reportWebVitals";
Remove import.

2023-06-06 10:25 UTC, nazarrachunn commented on src/index.tsx
> +import "./index.css";
Done

2023-06-06 10:25 UTC, nazarrachunn commented on src/App.tsx
> +        {<p>{JSON.stringify(randomItem)}</p>}
Done

2023-06-06 10:25 UTC, nazarrachunn commented on src/index.tsx
>  // or send to an analytics endpoint. Learn more: https://bit.ly/CRA-vitals
Done

2023-06-06 10:25 UTC, nazarrachunn commented on src/index.tsx
> +import reportWebVitals from "./reportWebVitals";
Done

2023-06-06 16:41 UTC, taras-bilozir-globacap approved these changes
Looks good.

2023-06-06 17:45 UTC, merged